### ISSUE TITLE
Create flake

### ISSUE THREAD

**Issue by bnjmnt4n** [arqv/zig-overlay#1]
I wonder if it's possible to create a flake-based version of this.

~~Not too sure how it would handle downloading the list of binaries, unless we do that as a separate step outside of Nix.~~

**Comment by arqv** [comment]
closed by #1, thank you for the suggestion!

**Comment by bnjmnt4n** [comment]
Wow thanks for the swift reply and fast work, I was planning to look at creating one soon myself. Will test it out!

**Comment by arqv** [comment]
> Edit: working great ([ref](https://github.com/bnjmnt4n/ziglings/commit/b5d75a8690966e74e13fee1c02a9e2ef89ddb9c4))!
awesome 😄, glad to have helped
